### PR TITLE
Updated all dependencies to their latest versions + merged winit_input_helper directly into this library.

### PR DESCRIPTION
**Pull request by rydb**
This pr contains two changes:

1. All dependencies are now updated to their latest versions.

There are two warnings now for using deprecated functions in winit, but I couldn't figure out how to get those updated for winit 0.30, so I just used those for expediency.

2. merged winit_input_helper directly into this lib.

winit_input_helper is only a few hundred lines long, has no dependencies other then winit, and it is currently abandoned as far as I can tell, but it was the sole blocker of updating winit. I just merged the two files it uses into this project, so that when winit/wgpu updates again, it will no longer be a blocker as it was before.

### CODE REVIEW

**Comment by Azkellas** [comment]
Thanks for the pr. I wanted to wait until all the dependency chain winit-wgpu-egui-...  was resolved but it has been pending for way too long because of the new api in winit 0.30 and winit-input-helper stalling. 
I think we can vendor the helper in the meantime.

I'm surprised you managed to update to winit 0.30 while keeping the current event loop though. I think it would be better to migrate to the new `ApplicationHandler` API to keep this project idiomatic and up-to-date (while also cleaning the dreadful runner).
I recently implemented it in my own project (which used this project as template), though I haven't tested it on wasm.  `winit-input-helper` has a pending [PR](https://github.com/rukai/winit_input_helper/pull/63) to support it that we can vendor instead of the main repo.

Would you like to try it out? Otherwise I can probably work on it this week-end.

Thanks for the help!

**Comment by rydb** [comment]
> Thanks for the pr. I wanted to wait until all the dependency chain winit-wgpu-egui-... was resolved but it has been pending for way too long because of the new api in winit 0.30 and winit-input-helper stalling. I think we can vendor the helper in the meantime.
> 
> I'm surprised you managed to update to winit 0.30 while keeping the current event loop though. I think it would be better to migrate to the new `ApplicationHandler` API to keep this project idiomatic and up-to-date (while also cleaning the dreadful runner). I recently implemented it in my own project (which used this project as template), though I haven't tested it on wasm. `winit-input-helper` has a pending [PR](https://github.com/rukai/winit_input_helper/pull/63) to support it that we can vendor instead of the main repo.
> 
> Would you like to try it out? Otherwise I can probably work on it this week-end.
> 
> Thanks for the help!

which project?

**Comment by Azkellas** [comment]
Sadly it's closed source (and diverged too much to be comparable), but examples in the winit input helper PR I linked above could serve as a good reference point too.

**Comment by rydb** [comment]
fixed WASM import. CI should pass now.

**Comment by Azkellas** [comment]
I had a go at using the new winit api. No issue for native and rust hot reload, but getting it to work in wasm is a bit tricky. 
I'll do it in a separate pull request I think.

**Pull request merged**
