### PR TITLE
Genericized naming conventions and placed demos and their pipelines into their own folder.

### PR DESCRIPTION
**Pull request by rydb**
This pr moves the demos into a demo_pipelines folder and genercizes the naming conventions in the demos.

Due to the restrictions of hot-loading, shaders hot-loaded by the library have to be within the library it self. This pr seperates code demoing the library(the shader pipelines, demo-shaders) into their own `demos`/`demo-pipelines` so the distinction between the library and its demos are clearer.

requires: #74

### CODE REVIEW

**Comment by Azkellas** [comment]
Good idea thanks.


> Due to the restrictions of hot-loading, shaders hot-loaded by the library have to be within the library it self. 

Where would you like to put them? Technically we could have a shader builder per pipeline, e.g.
```rust
/// Shader helpers
/// Will load from file in native debug mode to allow reloading at runtime
/// and embed in binary in wasm/release mode.
///
/// To make it work, the struct must derive `RustEmbed` and specify a source folder.
/// ```ignore
/// #[derive(RustEmbed)]
/// #[folder = "shaders"]
/// pub struct MyShaderBuilder;
///
/// impl ShaderBuilderTrait for MyShaderBuilder {}
/// ```
pub trait ShaderBuilderTrait: RustEmbed {
   ... // Same code as before
}
```

and modify the watcher to watch the correct folder (by exposing it in the Program trait) but I'm not sure where you would like to put them in the current architecture.

Also would it make sense to rename the `Program` trait? `impl Program for Pipeline` bothers me a bit.

**Comment by rydb** [comment]
> Good idea thanks.
> 
> > Due to the restrictions of hot-loading, shaders hot-loaded by the library have to be within the library it self.
> 
> Where would you like to put them? Technically we could have a shader builder per pipeline, e.g.
> 
> ```rust
> /// Shader helpers
> /// Will load from file in native debug mode to allow reloading at runtime
> /// and embed in binary in wasm/release mode.
> ///
> /// To make it work, the struct must derive `RustEmbed` and specify a source folder.
> /// ```ignore
> /// #[derive(RustEmbed)]
> /// #[folder = "shaders"]
> /// pub struct MyShaderBuilder;
> ///
> /// impl ShaderBuilderTrait for MyShaderBuilder {}
> /// ```
> pub trait ShaderBuilderTrait: RustEmbed {
>    ... // Same code as before
> }
> ```
> 
> and modify the watcher to watch the correct folder (by exposing it in the Program trait) but I'm not sure where you would like to put them in the current architecture.

I'm probably going to have a fork of this repo with shaders Im testing with a `/my_shaders` folder in /lib/src. I don't know if the lib will hot-reload my shaders/pipelines if its not directly in the project, so I'm doing that for the moment.

> Also would it make sense to rename the `Program` trait? `impl Program for Pipeline` bothers me a bit.

Done. I wasn't a fan of the name either. I renamed `Program` to `PipelineFuncs`. Now its `impl PipelineFuncs for Pipeline`

**Comment by Azkellas** [comment]
> I'm probably going to have a fork of this repo with shaders Im testing with a /my_shaders folder in /lib/src. I don't know if the lib will hot-reload my shaders/pipelines if its not directly in the project, so I'm doing that for the moment.

To be hot-reloadable, shaders need two things:
- be in a folder tracked by a `ShaderBuilder`
- be in a folder watched by `src::main.rs::watch()` to notify the lib of changes

For the first point the snippet above should work. For the second point, we could add a `get_shader_folder` method in the `PipelineFuncs` so at runtime we would know where to watch for changes.

This is entirely optional though, tell me if you think it's worth it or if the PR is ready as-is.

**Comment by rydb** [comment]
> > I'm probably going to have a fork of this repo with shaders Im testing with a /my_shaders folder in /lib/src. I don't know if the lib will hot-reload my shaders/pipelines if its not directly in the project, so I'm doing that for the moment.
> 
> To be hot-reloadable, shaders need two things:
> 
>     * be in a folder tracked by a `ShaderBuilder`
> 
>     * be in a folder watched by `src::main.rs::watch()` to notify the lib of changes
> 
> 
> For the first point the snippet above should work. For the second point, we could add a `get_shader_folder` method in the `PipelineFuncs` so at runtime we would know where to watch for changes.
> 
> This is entirely optional though, tell me if you think it's worth it or if the PR is ready as-is.

I would say its worth it. I'd like to have my shaders/pipelines in their own repos to test them. Not sure where to begin with adding the `get_shader_folder` function though, but I'll look at it.

**Comment by rydb** [comment]
> > I'm probably going to have a fork of this repo with shaders Im testing with a /my_shaders folder in /lib/src. I don't know if the lib will hot-reload my shaders/pipelines if its not directly in the project, so I'm doing that for the moment.
> 
> To be hot-reloadable, shaders need two things:
> 
>     * be in a folder tracked by a `ShaderBuilder`
> 
>     * be in a folder watched by `src::main.rs::watch()` to notify the lib of changes
> 
> 
> For the first point the snippet above should work. For the second point, we could add a `get_shader_folder` method in the `PipelineFuncs` so at runtime we would know where to watch for changes.
> 
> This is entirely optional though, tell me if you think it's worth it or if the PR is ready as-is.

After thinking about this more, making it easier to debug shaders outside of the library is probably better chunked into several smaller PRS. In the meantime though, I changed ShaderBuilder to be generic so it can accept arbitrary folders via its T generic.

This pr is good to go, assuming its dependent pr gets merged.

**Comment by Azkellas** [comment]
> After thinking about this more, making it easier to debug shaders outside of the library is probably better chunked into several smaller PRS. In the meantime though, I changed ShaderBuilder to be generic so it can accept arbitrary folders via its T generic.

Nicely done.

I merged #74, can you rebase on the new trunk and rename the `program.rs` file with respect to its new content? Thanks for contributing. :)

**Comment by Azkellas** [comment]
I took the liberty to squash the commits as the history was quite polluted by the merge from #74.

Thanks for contributing!

**Pull request merged**
